### ISSUE TITLE
Very long boot time

### ISSUE THREAD

**Issue by HQv2** [Botspot/wor-flasher#118]
## Setup:

- **Which version of Windows you chose:** 11
- **Raspberry Pi model:** 4B 8GB
- **Name of SD card you tried to flash (some are too slow or too small):** Samsung 128GB Evo Plus
- **What day you first downloaded wor-flasher:** 2023-03-13
- **What linux operating system you are using to run wor-flasher on:** Raspberry Pi OS

Hello,

Windows 11 has installed successfully and works well, but every time I power on or reboot the device, it hangs on the black Raspberry screen for about 10 minutes. Is this normal?

![IMG_2849](https://user-images.githubusercontent.com/42633588/224830392-d6eb5e5a-1411-4fc7-83dc-4d3c459025aa.jpg)

Thank you!

**Comment by HQv2** [comment]
Resolved by changing the boot order. It then started getting stuck on automatic repair and wouldn't boot, so I gave up on this.

**Comment by Botspot** [comment]
The 10 minute delay happens on every boot for everybody. From what I understand, this is due to some issue on Window's side. As nobody but Microsoft understands how Windows works, the free world is more or less powerless to improve it.

Your options are:
- To stop using Windows (recommended)
- To put up with the delay
- To hack microsoft and leak the Windows source code so some WoR developers can make workarounds. (obviously, not recommended at all)
