### ISSUE TITLE
windows 11 on raspberry pi 5: NO wifi or wiried connection

### ISSUE THREAD

**Issue by Leaf239** [Botspot/wor-flasher#148]
i just use wor installer (https://github.com/Botspot/wor-flasher), but i cannot connect internet. as Diagnostic results, somthing wrong with driver.
HELP ME PLEASE!!

**Comment by Botspot** [comment]
This is a known issue and I have written about it on the "Useful information" section.

Did you read that?
![20240213_08h58m22s_grim](https://github.com/Botspot/wor-flasher/assets/54716352/c23d5bc5-bcbe-4319-97b4-89c6f5f10a65)
If you did not see that earlier, can you think of a better place for me to put the information so that people like you will actually read the important information?

**Comment by Leaf239** [comment]
oh, I understand. there has no driver for raspi 5. Thank You!

**Comment by Leaf239** [comment]
When do you plan to update the driver for the Pi 5 so that it can be installed, @Botspot ?

**Comment by Botspot** [comment]
Only the wifi module manufacturer could, and they would need help from microsoft. That will never happen.

**Comment by Leaf239** [comment]
Never able to use the internet?

**Comment by Botspot** [comment]
Use a USB to Ethernet adapter.

**Comment by Leaf239** [comment]
Ok. I'll buy USB Adapter on Amazon.

**Comment by Botspot** [comment]
Or pair your phone to it the way leepspvideo did here: https://www.youtube.com/watch?v=haeYUq4RHbk

**Comment by Leaf239** [comment]
Thanks! But I've already bought an adapter and I'm using it. LOL

**Comment by Leaf239** [comment]
What a nice way!

**Comment by Goldfelty** [comment]
I imagine there could be a way to take a driver form the galaxy S2 1st ultra which uses the same chip and format this into something windows can understand
