### ISSUE TITLE
Add Pi Zero support

### ISSUE THREAD

**Issue by Ocean-OS** [Botspot/wor-flasher#149]
I've been wanting to have at least semi-support for running Windows 11/10 on the Pi Zero (Specifically the Pi Zero 2 W). Although I know it would be very slow, I would still like to have some sort of supported solution for this.

**Comment by Botspot** [comment]
Try this setup:
- Windows 10
- Pi3
The Pi zero 2 uses essentially the same processor as the pi3, so maybe it will work. It is unlikely though due to the lower RAM. 1GB was not really practical. It's hard to make just the OS use less than 1GB.

So I doubt anything with half a gigabyte of RAM could run windows, though you are welcome to try.

Closing this issue, as there is nothing I can do. Windows on RPi is actually a separate project. I only maintain the flasher that runs on Linux. This kind of request is not my specialty.
