### ISSUE TITLE
32 Bit Support

### ISSUE THREAD

**Issue by actraiser30** [Botspot/wor-flasher#15]
Hello,great tool

is it possible to add support to install 32 Bit windows 10 and windows 11 also ??

and if possible to add windows 7 and windows 8.1 in the installer ??

thanks

**Comment by Botspot** [comment]
> Hello,great tool
> 
> is it possible to add support to install 32 Bit windows 10 and windows 11 also ??

No, this is not possible. The Raspberry Pi uses an ARM-based CPU. It's completely different than a conventional PC's x86 processor.
For a conventional PC, you could install Windows 32-bit or 64-bit on it. But for ARM, Microsoft has only ever released a 64-bit ARM release. This ARM64 release is what WoR-flasher uses. I suppose that if Microsoft releases 32-bit ARM Windows, it could be added here. But why? It would only run slower than the 64-bit variant, and in every way be inferior.
The ARM64 version of Windows features an emulator that lets you install and run conventional x86 apps. 

> and if possible to add windows 7 and windows 8.1 in the installer ??

No. Microsoft never released an ARM build of Windows 8.1 or Windows 7, probably because ARM computers were less popular than they are today.
