### ISSUE TITLE
Monitor Resolution 

### ISSUE THREAD

**Issue by Chobber** [Botspot/wor-flasher#62]
Wherever and however I install Windows on a pi 4 AND 400 I cannot get a readable monitor resolution. It is so much pixeled that one cannot read anything. I tested that also on 3 different monitors- also regardless if SD, USB or SSD. The only way it works is in combination with the Argon M2 case … but this is not an option for me.

**Comment by Botspot** [comment]
How a chunk of metal surrounding the pi could solve a software problem is beyond me, but unfortunately I cannot be of help.
This sounds like a problem with Windows or with the firmware used to boot windows. Perhaps it's caused by some sort of weird HDMI signal interference?

In any case, I can't really be of help. :(
