### ISSUE TITLE
Legal

### ISSUE THREAD

**Issue by Maki2007** [Botspot/wor-flasher#69]
Is this legal at all? 
This is not something there hacks into ms server, to get the OS?
I dont want to get a big thicket.

**Comment by Botspot** [comment]
Short answer: Yes.

Microsoft doesn't provide a ready-made ARM image (yet), but it does publicly distribute all of the components necessary to build one. Microsoft mainly does this so that large computer/laptop manufacturers can build their own customized Windows images, but it's perfect for WoR-Flasher as well.

If you use this flasher, Windows will ask you for a license key, just like any other ordinary installation.
Of course, I may be **lying**. How can you trust me? In that case, go read through [this discussion](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=318599) on the Raspberry Pi Forums. Several folks were arguing that this was illegal, but eventually some Raspberry Pi employees came out and [confirmed](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=318599#p1907313) that WoR-Flasher is perfectly legal.

**Comment by Maki2007** [comment]
Ok, now I understand how it is

**Comment by Botspot** [comment]
@Maki2007, Thank you for reaching out. If you need anything else, please let me know!

**Comment by Maki2007** [comment]
Ok thanks for help:-)
